### ISSUE TITLE
Complete the CommonHTML output

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1051]
This is a meta-issue.

* [x] add webfonts support
* [x] #1035  improve fractions
* [x] proper stretchy characters
* [x] stretchy embellished operators
* [x] support `mtable` attributes
* [x] variable-width `mtable` elements
* [x] #968  add `mlabeledtr` support
* [x] TeX versus MathML spacing
* [x] allow `mtextInheritFont`
* [x] support `mathsize` attribute
* [x] match font heights
* [x] support `displayAlign` and `displayIndent`
* [x] support line breaking
* [x] bevelled fractions
* [x] handle hrefs, class, and other attributes
* [x] support `maction`
* [x] support `menclose`
* [x] support `ms`
* [x] support `mglyph`
* [x] support `mphantom`
* [x] support `mmultiscripts`
* [x] handle VCENTER TeXAtom
* [x] add `isMathJax` to created nodes
* [x] handle zoom action
* [x] update web fonts
* [x] https://github.com/mathjax/MathJax-dev/issues/11 create new combined configurations with CommonHTML as default
* [x] Fix font displayed in the About MathJax box.

What else?

**Comment by booleanbetrayal** [comment]
Really looking forward to this release @pkra !

**Comment by dpvc** [comment]
=> Merged  (the `chtml` branch has been merged into `develop`).

**Comment by pkra** [comment]
:party:

**Comment by barillax** [comment]
:beers:

**Comment by pkra** [comment]
@dvpc the about window shows "generic fonts" right now (with local fonts installed). IIUC, that's in the menu code. Should I open a separate issue?

**Comment by booleanbetrayal** [comment]
:clap:

**Comment by dpvc** [comment]
> the about window shows "generic fonts" right now

OK, I've fixed that.

**Comment by dpvc** [comment]
I think this is complete at this point, so I'm closing it.  Bugs with CommonHTML output should get their own issues at this point.
