### ISSUE TITLE
Meta issue: accessibility

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1116]
Add more APIs for accessibility tools (AT) to allow AT to interact with MathJax rendering as if it was native MathML such as
- [X] MathJax menu and accessibility #939, #1119, #1093
- [X] exposing MathML, e.g., #938 
- [ ] exposing source formats,  #788,  #1105
- [X] aria role for SVG output #1192
- [x] provide navigation information
- [x] provide summary information
- [x] enable synchronized highlighting 
- [ ] subexpression APIs #1108 
- [x] embed speech-text generation for/from AT
- [ ] interact with accessibility preferences for AT
- [ ] improve compatibility with user style sheets
- [ ] Investigate ShadowDOM / web components potential for accessibility, cf #1106
