### ISSUE TITLE
[Meta] RTL / BiDi support

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1311]
- [ ] #1025: bugs in the experimental mml3.js extension
- [ ] UI issues
  - #628: menu location)
  - #601: mixing RTL and LTR in the UI
- [ ] #474: Complex Layout (e.g., Unicode characters)
- [ ]  #610: RTL support in MathML
  - hacks for TeX input: https://github.com/mathjax/MathJax/issues/610#issuecomment-135366695
  - [ ] #1308: support mirrored roots

**Comment by pouriaMaleki** [comment]
I have written dirty code, maybe useful for now:

    var texts = document.querySelectorAll(".mjx-mtext");
    for (var i = 0; i < texts.length; i++)
        if (textContainArabic(texts[i].innerText)) 
               texts[i].innerHTML = texts[i].innerText;
