### ISSUE TITLE
Asciimathml meta issue for 2.x

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#857]
This issue is for keeping track of asciimathml changes which should be pulled back into MathJax for the next release.
- [x] mathjax/asciimathml#14 -- switching `phi` and `varphi`, i.e., changing the defaults we set in #353
- [x] mathjax/asciimathml#19 -- leading space in quotes problem #883
- [x] #851
- [x] power of f and g #431
- [x] underscore #741
