### ISSUE TITLE
Meta-issue: queue enhancements

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#875]
A couple of queue enhancements have cropped up over time. This issue thread is trying to collect them.
- [x] #872 (Add delays to typesetting)
- [x] #873 (combine array of elements)
- [ ] better support for clearing the queue 
  - this came up on the User Group but I can't find a link. 
  - use case: content has been replaced dynamically by new content but some equations from the original content are still on the queue (e.g., epub3 reading systems have this problem)
  - IIUC, right now MathJax will fail gracefully if the original element disappears but it will still typeset the equations.
  - See also #933

What else?

**Comment by episodeyang** [comment]
a general cancel all typesetting sounds good enough.

**Comment by episodeyang** [comment]
Hi, @dpvc 

What's our update on this? I would LOVE to have this feature!

If possible, the code that's currently used by stack overflow would be useful for me too, since we desperately need this feature and I can just patch up my app for the time being (or submit a PR!)

Ge

**Comment by dpvc** [comment]
I'm not sure when this will be implemented.  There is some code [here](http://www.math.union.edu/locate/Cervone/transfer/mathjax/mathjax-editing.js) near the bottom that does something like what you are after.  You might be able to extract that for now.

**Comment by episodeyang** [comment]
Okay this is Golden! Thanks a bunch!!!!
