### ISSUE TITLE
meta-bug: table improvements

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#876]
Meta-issue to collect improvements for mtable implementation
- [ ] displaystyle inheritance, #839
- [ ] styling of rows #859
- [ ] relative width in SVG #757
- [ ] implement colspan, rowspan #1102
  - this would enable macros like border matrix, split #390
- [ ] implement elementary math, cf. #1101 (ok, not strictly mtable but obviously related)
- [ ] linebreaking within tables #957
